### ISSUE TITLE
Decide on a naming standard for new and imported hours

### ISSUE THREAD

**Issue by ilix** [Iteam1337/izone-google-calendar#2]
Today we use : and ; which are no good.

**Suggestions**

- (vimla) => [vimla]
- vimla¤ => vimla$
- vimla:: => vimla#
- vimla-- => vimla++

**Comment by irony** [comment]
I'd rather not change the source at all but rather save an ID in the database for each item that has already been imported.

**Comment by irony** [comment]
We have already started this in the jl_job_log_db table - there is a exchange id - we could use that to also be able to update already imported hours with new changes.

**Comment by irony** [comment]
Either we change the column name to something like `source_id` or we create new columns for all sources we add.

**Comment by ilix** [comment]
I agree. Izone now saved Google calendar's id of each time entry when importing.
