### ISSUE TITLE
Warn user if alias matches > 1 job in database (and do not allow time reporting)

### ISSUE THREAD

**Issue by ilix** [Iteam1337/izone-google-calendar#5]
This basically means that the alias for a certain event is used in more than one project/job in izone, which is pretty bad. The CLI can not be 100 % which one to pick, so whoever is responsible for planning that particular project should fix this in izone.

**Comment by irony** [comment]
This is perfect. Should have been added long time ago in old izone too..

**Comment by ilix** [comment]
Fixed in 0.0.9
